%YAML 1.2
---
command:
  name: goal
  _inactive: true
  description: manage goals
  usage: goal [options] <command>
  commands:
    -
      name: show
      description: Show a particular goal.
      usage: show [options] <id>
      _inactive: true
      examples:
        -
          example: goal show 12
          description: Show goal with id 12.
    -
      name: create
      description: Create a new goal.
      usage: create [options] [<title>]
      _inactive: true
    -
      name: search
      description: Search for goals by title.
      usage: search [options] <query>
      _inactive: true
  examples:
    -
      example: goal show 12
      description: Show goal with id 12.
    -
      example: goal search --help
      description: Get help on searching for goals.
