%YAML 1.2
---
command:
  name: learner
  _inactive: true
  description: manage learners
  usage: learner [options] <command>
  commands:
    -
      name: status
      description: Check status of a learner.
      usage: status [options] [<@handle>]
      _inactive: true
      examples:
        -
          example: learner status
          description: View your own status.
        -
          example: learner status @jaime
          description: View status of learner with handle @jaime.
    -
      name: play
      description: Activate learner for current cycle.
      usage: play [options] <@handle>
      _inactive: true
    -
      name: pause
      description: Deactivate learner for current cycle.
      usage: pause [options] <@handle>
      _inactive: true
  examples:
    -
      example: learner status
      description: View your own status.
    -
      example: learner pause --help
      description: Get help on pausing game play.
