%YAML 1.2
---
command:
  name: log
  _inactive: true
  description: log reflections
  usage: log [options] [response]
  options:
    -
      name: retro
      abbr: r
      boolean: true
      help: Show list of retrospective questions for current retrospective. Use in conjunction with the `-q<index>` option to display and respond to retrospective questions.
    -
      name: question
      abbr: q
      help: Show a question using its index. Provide a response argument to log a response for the question.
    -
      name: project
      abbr: p
      help: Only required if you are working on multiple projects in the same cycle.
  examples:
    -
      example: log --retro
      description: Show retrospective status and list of questions.
    -
      example: log -r -q2
      description: Show retrospective question with index 2.
    -
      example: 'log -r -q2 --project #fancy-dingo "So far so good"'
      description: 'Respond to retrospective question 2 for the #fancy-dingo project'
    -
      example: log -r -q2 "So far so good"
      description: Respond to retrospective question 2 with a message.
    -
      example: log -rq 2 "So far so good"
      description: Alternate option syntax for responding to retrospective question 2.
