%YAML 1.2
---
command:
  name: retro
  description: log retrospective reflections
  usage: retro [options] [<project id>]
  examples:
    -
      example: 'retro #stable-snake'
      description: 'Begin retrospective survey for the #stable-snake project'
    -
      example: 'retro'
      description: Begin retrospective survey for your current project
